# Generated by Django 3.2.9 on 2021-11-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation_details', '0002_auto_20211118_1954'),
        ('employees', '0005_auto_20211118_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=45)),
                ('leave_days', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year', models.IntegerField()),
                ('entitlement', models.IntegerField(default=21)),
                ('residue', models.IntegerField(default=0)),
                ('leave_applied', models.IntegerField(default=0)),
                ('total_taken', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField(default=1)),
                ('supervisor_status', models.CharField(default='Pending', max_length=15)),
                ('supervisor_comment', models.TextField(blank=True, default='None', null=True)),
                ('hod_status', models.CharField(default='Pending', max_length=15)),
                ('hod_comment', models.TextField(blank=True, default='None', null=True)),
                ('hr_status', models.CharField(default='Pending', max_length=15)),
                ('hr_comment', models.TextField(blank=True, default='None', null=True)),
                ('overall_status', models.CharField(default='Pending', max_length=10)),
                ('remarks', models.TextField(default='None')),
                ('balance', models.IntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='employees.employee')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='employees.employee')),
                ('hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leave_types')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='employees.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_details.team')),
            ],
        ),
        migrations.AddField(
            model_name='leave_types',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaverecord'),
        ),
    ]
