# Generated by Django 3.2.9 on 2021-11-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_types',
            name='total_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_types',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Special', 'Special Leave')], default='Annual', max_length=45),
        ),
        migrations.AlterField(
            model_name='leave_types',
            name='record',
            field=models.ForeignKey(limit_choices_to={'leave_year__in': [2021, 2022]}, on_delete=django.db.models.deletion.CASCADE, to='leave.leaverecord'),
        ),
    ]
