# Generated by Django 3.2.9 on 2021-11-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='damage',
            new_name='amont',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='national_id',
            new_name='PAN',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nssf_no',
            new_name='aadhar_id',
        ),
        migrations.RenameField(
            model_name='spouse',
            old_name='national_id',
            new_name='gov_id_card',
        ),
        migrations.RenameField(
            model_name='statutorydeduction',
            old_name='local_service_tax',
            new_name='amont',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='police_fine',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='salary_advance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='annual_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='balance_last_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='local_service_tax',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ura_tin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_station',
        ),
        migrations.RemoveField(
            model_name='homeaddress',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='homeaddress',
            name='sub_county',
        ),

        migrations.AddField(
            model_name='allowance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='bank_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_cto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_recruter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statutorydeduction',
            name='name',
            field=models.CharField(choices=[('ptax', 'PTAX'), ('ghi', 'GHI')], default='ptax', max_length=40),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(default='Bonus', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notish', 'In Notish'), ('deactive', 'Old employee')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='alien_certificate_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='immigration_file_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='nationality',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='passport_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
