# Generated by Django 3.2.9 on 2021-11-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PAN',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='aadhar_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nationality',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lunch_allowance',
            new_name='tea_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='residence_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='telephone_no',
        ),
    ]
