# Generated by Django 3.2.9 on 2021-11-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20211118_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='Manager',
        ),
        migrations.AddField(
            model_name='manager',
            name='lead_type',
            field=models.CharField(choices=[('tl', 'Team Lead'), ('pm', 'Project Manager')], default='tl', max_length=5),
        ),
        migrations.AddField(
            model_name='manager',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers_supervisor', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='employees.employee'),
        ),
    ]
