# Generated by Django 3.2.9 on 2021-11-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20211118_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutorydeduction',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statutorydeduction',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='name',
            field=models.CharField(choices=[('ptax', 'PTAX'), ('ghi', 'GHI')], default='ptax', max_length=40),
        ),
        migrations.AlterField(
            model_name='statutorydeduction',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amont', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
