# Generated by Django 3.2.9 on 2021-11-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20211124_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
