# Generated by Django 3.2.9 on 2021-11-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_deduction_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='amont',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees.employee'),
        ),
    ]
