# Generated by Django 3.2.9 on 2021-11-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20211124_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee'),
        ),
    ]
