# Generated by Django 3.2.9 on 2021-12-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_allowance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='statutorydeduction',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Allowance',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='StatutoryDeduction',
        ),
    ]
