# Generated by Django 3.2.9 on 2021-12-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='resolved',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('formula', 'Formula'), ('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=100)),
                ('condition', models.CharField(default='1', max_length=500, verbose_name='Condition when this apply')),
                ('type', models.CharField(choices=[('BA', 'Basic Salary'), ('HRA', 'House rent'), ('DA', 'Daily Allowance'), ('PF', 'P Tax'), ('ESIC', 'ESIC'), ('GHI', 'Health Cover'), ('TDS', 'TDS'), ('BO', 'Bonus'), ('INC', 'Incentive'), ('other', 'Other')], max_length=100)),
                ('code', models.CharField(choices=[('DED', 'Deduction'), ('ALL', 'Allowance')], max_length=100)),
                ('amount', models.CharField(max_length=500, verbose_name='Total amount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.contract')),
            ],
        ),
    ]
