# Generated by Django 3.2.9 on 2021-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='experience in Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='refer_by',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
