# Generated by Django 3.2.9 on 2021-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_auto_20211115_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Evalution in year exp.'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating out of 10'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Put remark here'),
        ),
    ]
