# Generated by Django 3.2.9 on 2021-11-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20211115_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('expected', models.IntegerField(default=0)),
                ('offered', models.IntegerField(default=0)),
                ('notice', models.CharField(max_length=100)),
                ('expected_doj', models.CharField(max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctc', to='recruiting.candidate')),
            ],
        ),
    ]
