# Generated by Django 3.2.9 on 2021-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='USD', max_length=10, unique=True)),
                ('desc', models.CharField(default='US Doler', max_length=20)),
                ('cost', models.CharField(default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HiringConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_welcome_email', models.BooleanField(default=False, verbose_name='Welcome email after Cv added')),
                ('send_resume_sortlisted_email', models.BooleanField(default=False, verbose_name='God fit for Interview, selected Proceess Cv')),
                ('send_resume_rejected_email', models.BooleanField(default=False, verbose_name="Con't Proceess for interview")),
                ('send_selected_email', models.BooleanField(default=False, verbose_name='Selected After Interview')),
                ('send_rejected_email', models.BooleanField(default=False, verbose_name='Rejected after Interview')),
                ('send_video_interview_email', models.BooleanField(default=False, verbose_name='Created Auto interview for video round')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Year')),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
            ],
        ),
    ]
